on:
  workflow_dispatch:
  push:
    branches: [master]

name: Playing with actions

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Build image
        id: tag
        run: |
          echo "Building"

  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploying image
        id: deploy
        run: |
          echo "Deploying image"
        if: github.event.review.state == 'approved'
