on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - "non-prod"
          - "prod"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ inputs.environment }} - Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: docker.io/library/alpine
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Output meta data
        shell: bash
        run: |
          echo ${{ steps.meta.outputs }}
