on:
  workflow_dispatch:
    inputs:
      active:
        description: Set container as active
        required: true
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: normal run
        run: |
          echo "This is always run"
      - name: set active
        if: ${{ inputs.active }} == 'yes'
        run: |
          echo "Will only run when you selected active 'yes'"
