on:
  workflow_call:
    inputs:
      container_tag:
        description: "Tag of container"
        required: true
        default: "test1"
        type: string
      environment:
        description: "Environment to deploy container"
        required: false
        default: "non-prod"
        type: string

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        id: tag
        run: |
          echo "Building ${{ inputs.container_tag }}"

  push:
    name: Push container to ECR
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Push container to ECR
        run: |
          echo "Pushing container ${{ inputs.container_tag }}"
