on:
  workflow_call:
    inputs:
      container_tag:
        description: "Tag of container"
        required: true
        default: "test1"
        type: string

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        id: tag
        run: |
          echo "Building"

  push:
    name: Push container to ECR
    needs: build
    runs-on: ubuntu-latest
    environment: non-prod

    steps:
      - name: Push container to ECR
        run: |
          echo "Pushing container"
