on:
  workflow_call:
    inputs:
      container_tag:
        description: "Tag of container"
        required: true
        default: "test1"
        type: string

name: Playing with actions

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        id: tag
        run: |
          echo "Building"
