on:
  workflow_dispatch:
    inputs:
      active:
        description: Set container as active
        required: true
        type: choice
        options:
          - "yes"
          - "no"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: normal run
        env:
          active: ${{ inputs.active == 'yes' }}
        run: |
          echo "TEST123=$(date)"
          echo "This is always run $active"
      - name: set active
        if: ${{ inputs.active == 'yes' }}
        run: |
          echo "Will only run when you selected active 'yes'"
          echo "$TEST123"
