on: pull_request_review

name: Playing with actions

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Build image
        id: tag
        run: |
          echo "Building"

  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest
    needs: build
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - uses: taichi/approved-event-action@v1.2.1
        id: approved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploying image
        id: deploy
        run: |
          echo "Deploying image"
        if: steps.approved.outputs.approved == 'true'
