on: pull_request_review
types: [submitted]

name: Playing with actions

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    env:
      PUSH_PACKAGES: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

    steps:
      - name: Build image
        id: tag
        run: |
          echo "Building"

  deploy:
    if: github.event.review.state == 'approved'
    name: Deploy Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: sakhnovict/multi-approved-event-action@1.0.3
        id: approved
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploying image
        id: deploy
        run: |
          echo "Deploying image"
        if: steps.approved.outputs.isApproved == 'true'
