name: container-cicd

on:
  push:
  workflow_dispatch:

jobs:
  non-prod:
    name: Build non-production container
    uses: ./.github/workflows/build-and-push.yaml
    with:
      environment: "non-prod"
      container_tag: "1234"
      registry: "blabla-non-prod"
      container_name: "container1"

  prod:
    name: Build production container
    uses: ./.github/workflows/build-and-push.yaml
    with:
      environment: "prod"
      container_tag: "qwerty"
      registry: "blabla-prod"
      container_name: "container2"
