name: container-cicd

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deploy into
        required: true
        type: choice
        options:
          - non-prod
          - prod

jobs:
  build-container-cicd:
    name: Build container
    uses: ./.github/workflows/build-and-push.yaml
    with:
      environment: "${{ inputs.environment }}"
      container_tag: "1234"
      registry: "blabla-${{ inputs.environment }}"
      container_name: "container1"
